"use client";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const disableNav = ["/auth/login", "/auth/register"];

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        {!disableNav.includes(pathName) && <Navbar />}
        {children}
      </body>
    </html>
  );
}
